# Generated by Django 5.1 on 2024-09-03 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_tema_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='palavra',
            name='texto',
        ),
    ]
