# Generated by Django 5.1 on 2024-09-11 04:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_palavra_texto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jogo',
            name='acertou',
        ),
        migrations.RemoveField(
            model_name='jogo',
            name='data_jogo',
        ),
        migrations.AddField(
            model_name='jogo',
            name='letras_corretas',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jogo',
            name='letras_erradas',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jogo',
            name='tentativas_restantes',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='jogador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
