# Generated by Django 5.1 on 2024-09-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_jogo_acertou_remove_jogo_data_jogo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jogo',
            name='tentativas_restantes',
            field=models.IntegerField(default=5),
        ),
    ]
